Create an array of 10 objects
htmlacademy-javascript/1875081-keksobooking-26 pull request #3
Opened 2022-06-05 12:21 UTC by AlyonaPrikhodchenko

2022-06-05 12:31 UTC, AlyonaPrikhodchenko commented on js/main.js
> +// ВЫШЕ МОЕ РЕШЕНИЕ, СНИЗУ АКАДЕМОВСКОЕ. АКАДЕМОВСКИЙ ВАРИАНТ, СУДЯ ПО ВСЕМУ, ЛУЧШЕ МОЕГО.
Скажи, мне оставить академовское решение? Пока не удаляла свое, только заккоментировала. Мне кажется академовское лучше.

2022-06-05 12:31 UTC, AlyonaPrikhodchenko commented on js/main.js
> +// В условии аватары не должны повторяться, я не уверена, что рандомное число - это то, что нужно, потому что в таком случае число может повторится несколько раз.
Ну вот, собственно, в комментарии описала свои сомнения. Нужно что-бы числа не повторялись, я не пойму, как это сделать при рандомном выборе числа. Ниже пробовала другое решение, заккоментировала его пока, потому что при таком решении и вовсе всегда только число 01 подставляется.

2022-06-05 12:31 UTC, AlyonaPrikhodchenko commented on js/main.js
> +  adress: 'LOCATION.lat, LOCATION.lng',
Вот здесь не поняла так ли нужно вставлять или как-то иначе

2022-06-05 12:31 UTC, AlyonaPrikhodchenko commented on js/main.js
> +  type: 'palace, flat, house, bungalow, hotel',
Вот вопрос по всем подобным задачам, где нужно строку со значениями вставить, правильно ли я написала. Потому что в задании именно строка, а не массив строк.

2022-06-05 12:31 UTC, AlyonaPrikhodchenko commented on js/main.js
> +const adsNear = Array.from({length: 10}, createAds);
Вызывается в консоль 10 массивов с нужными объектами, вроде все как нужно, но они все одинаковые. Понятно, что пока что у нас нет всех условий, но, к примеру, у объекта AUTHOR в url число не меняется и у всех 10 массивов одинаковое. Я явно что-то делаю не так.

2022-06-05 12:31 UTC, AlyonaPrikhodchenko commented on js/main.js
> +const avatarNumbers = [
В целом нужно ли было создавать массив с числами для URLов? Или это лишнее и можно упростить? Если брать функцию рандомного целого числа, то, думаю, там просто можно задать диапазон, но опять же, меня вводит в ступор, что числа не должны повторятся. Так что вариант в использованием данной функции под вопросом.

2022-06-05 12:35 UTC, AlyonaPrikhodchenko commented on js/main.js
> +console.log(adsNear);
Из-за вывода в консоль при пулреквесте пишет, что проверка не пройдена, потому что это ошибка. Но когда я убираю вывод в консоль, ругается на ошибку, что const adsNear нигде не используется. Потому я не буду пока это дергать

2022-06-05 19:07 UTC, ademaro commented on js/main.js
> +// ВЫШЕ МОЕ РЕШЕНИЕ, СНИЗУ АКАДЕМОВСКОЕ. АКАДЕМОВСКИЙ ВАРИАНТ, СУДЯ ПО ВСЕМУ, ЛУЧШЕ МОЕГО.
Оставляй что больше нравится) И удаляй комментарии с кодом, если что — он есть в истории коммитов.

2022-06-05 19:13 UTC, ademaro commented on js/main.js
> +const avatarNumbers = [
Ну как минимум не надо было писать это «в лоб») Мы программисты, хотя бы что-то подобное:
```js
const avatarNumbers = Array.from({length: 10}, (x, i) => ++i);
```
Но и это на самом деле не нужно нам, ниже расскажу

2022-06-05 19:16 UTC, ademaro commented on js/main.js
> +const AUTHOR = {
То, что пишем капсом — это именно константные значения (то, что вычисляется при старте программы и не меняется. У тебя будет меняться (и вообще зачем отдельно делать такой объект?)

2022-06-05 19:16 UTC, ademaro commented on js/main.js
> +  adress: 'LOCATION.lat, LOCATION.lng',
address

2022-06-05 19:16 UTC, ademaro commented on js/main.js
> +const OFFER = {
У нас должна быть функция генерации объявления

2022-06-05 19:19 UTC, ademaro commented on js/main.js
> +  type: 'palace, flat, house, bungalow, hotel',
у тебя тут как раз строка, но должна быть одно значение из этого массива: `const TYPES = ['palace', 'flat', 'house', 'bungalow', 'hotel'];` Для удобства сделай функцию, которая будет выбирать случайное значение из массива: `getRandomElementFromArray(TYPES);`

2022-06-05 19:19 UTC, ademaro commented on js/main.js
> +  checkin: '12:00, 13:00, 14:00',
`getRandomElementFromArray(TIMES);`

2022-06-05 19:22 UTC, ademaro commented on js/main.js
> +  features: [
Набор фич должен генерироваться всегда разный для каждого объявления `getRandomElementsFromArray(FEATURES);` — обрати внимание, что это немного другая функция должна быть: выбираем не *один элемент* из массива, а _рандомное количество элементов_ из массива

2022-06-05 19:23 UTC, ademaro commented on js/main.js
> +  photos: [
тут так же хорошо бы сделать, что бы было 0, 1, 2 или 3 картинки (а не что бы всегда 3)

2022-06-05 19:24 UTC, ademaro commented on js/main.js
> +};
мы должны генерировать координаты для **каждого** объявления **разные**

2022-06-05 19:58 UTC, ademaro commented on js/main.js
> +const createAds = (function () {
тогда уж createAd (одно же делаем). Ну и выглядеть должно как-то так:
```js
// константное значение:
const TYPES = ['palace', 'flat', 'house', 'bungalow', 'hotel'];

// и вот это константные значения (мы запаковали в «перечисление» наши константы для удобства):
const Coords = {
  LAT_MIN: 35.65000,
  LAT_MAX: 35.70000,
  LNG_MIN: 139.70000,
  LNG_MAX: 139.80000
};

// пишем jsDoc (описание для нашей функции в специальном формате), а потом сразу объявление функции:
/**
 * Функция для генерации объявления
 * @param {integer} index — индекс изображения, который будем передавать при генерации списка объявлений
 * @return {Object} — готовый объект объявления
 */
const createAd = (index) => {
  const location = {
    lat: getRandomFloat(Coords.LAT_MIN, Coords.LAT_MAX),
    lng: getRandomFloat(Coords.LNG_MIN, Coords.LNG_MAX),
  };
  return {
    author: {
      avatar: `img/avatars/user${String(index).padStart(2, '0')}.png`
    },
    offer: {
      address: `${location.lat}, ${location.lng}`,
      type: getRandomElementFromArray(TYPES),
      features: getRandomElementsFromArray(FEATURES),
      // другие поля...
    },
    location
  };
};

// далее пишем функцию генерации **списка** объявлений:
/**
 * Генерация объявлений
 * @param {integer} count — количество объявлений, которое хотим сгенерировать
 * @return {Array} — массив сгенерированных объявлений
 */
const createAds = (count) => Array.from({length: count}, (x, i) => createAd(i));
```

2022-06-05 19:59 UTC, ademaro commented on js/main.js
> +console.log(adsNear);
да, это норм

2022-06-05 19:59 UTC, ademaro requested changes
Оставляю на доработку, если что-то непонятно — можем созвониться

2022-06-06 12:47 UTC, AlyonaPrikhodchenko commented
А еще при выводе в консоль браузер виснет, просто какая-то вечная перезагрузка происходит. Один раз только каким-то чудом все же в консоль вывелся массив объявления, но только один раз.
Вывожу так, например: `console.log(createAds(5));`

2022-06-06 16:46 UTC, ademaro commented
Зависает, тк входит в бесконечный цикл, смотри внимательнее там где while, поменяй на do .. while, например. Когда у тебя elementsLength становится максимальным значением, то цикл уходит в бесконечность.

2022-06-06 16:48 UTC, ademaro commented on js/main.js
> +    const randomElements = elements[getRandomInt(0, elements.length - 1)];
у тебя же уже есть функция getRandomElementFromArray, почему тут не используешь?)

2022-06-06 16:49 UTC, ademaro commented on js/main.js
> +};
давай константы и перечисления — в начало модуля (есть критерий, будем привыкать)

2022-06-06 16:50 UTC, ademaro requested changes
В целом всё круто, молодец! Давай совсем чутка подправим и закрою

2022-06-07 19:34 UTC, merged